using System.Xml.Linq;

namespace OpenXmlPowerTools
{
    public static class O
    {
        public static readonly XNamespace o = "urn:schemas-microsoft-com:office:office";

        public static readonly XName allowincell = o + "allowincell";
        public static readonly XName allowoverlap = o + "allowoverlap";
        public static readonly XName althref = o + "althref";
        public static readonly XName borderbottomcolor = o + "borderbottomcolor";
        public static readonly XName borderleftcolor = o + "borderleftcolor";
        public static readonly XName borderrightcolor = o + "borderrightcolor";
        public static readonly XName bordertopcolor = o + "bordertopcolor";
        public static readonly XName bottom = o + "bottom";
        public static readonly XName bullet = o + "bullet";
        public static readonly XName button = o + "button";
        public static readonly XName bwmode = o + "bwmode";
        public static readonly XName bwnormal = o + "bwnormal";
        public static readonly XName bwpure = o + "bwpure";
        public static readonly XName callout = o + "callout";
        public static readonly XName clip = o + "clip";
        public static readonly XName clippath = o + "clippath";
        public static readonly XName cliptowrap = o + "cliptowrap";
        public static readonly XName colormenu = o + "colormenu";
        public static readonly XName colormru = o + "colormru";
        public static readonly XName column = o + "column";
        public static readonly XName complex = o + "complex";
        public static readonly XName connectangles = o + "connectangles";
        public static readonly XName connectlocs = o + "connectlocs";
        public static readonly XName connectortype = o + "connectortype";
        public static readonly XName connecttype = o + "connecttype";
        public static readonly XName detectmouseclick = o + "detectmouseclick";
        public static readonly XName dgmlayout = o + "dgmlayout";
        public static readonly XName dgmlayoutmru = o + "dgmlayoutmru";
        public static readonly XName dgmnodekind = o + "dgmnodekind";
        public static readonly XName diagram = o + "diagram";
        public static readonly XName doubleclicknotify = o + "doubleclicknotify";
        public static readonly XName entry = o + "entry";
        public static readonly XName extrusion = o + "extrusion";
        public static readonly XName extrusionok = o + "extrusionok";
        public static readonly XName FieldCodes = o + "FieldCodes";
        public static readonly XName fill = o + "fill";
        public static readonly XName forcedash = o + "forcedash";
        public static readonly XName gfxdata = o + "gfxdata";
        public static readonly XName hr = o + "hr";
        public static readonly XName hralign = o + "hralign";
        public static readonly XName href = o + "href";
        public static readonly XName hrnoshade = o + "hrnoshade";
        public static readonly XName hrpct = o + "hrpct";
        public static readonly XName hrstd = o + "hrstd";
        public static readonly XName idmap = o + "idmap";
        public static readonly XName ink = o + "ink";
        public static readonly XName insetmode = o + "insetmode";
        public static readonly XName left = o + "left";
        public static readonly XName LinkType = o + "LinkType";
        public static readonly XName _lock = o + "lock";
        public static readonly XName LockedField = o + "LockedField";
        public static readonly XName master = o + "master";
        public static readonly XName ole = o + "ole";
        public static readonly XName oleicon = o + "oleicon";
        public static readonly XName OLEObject = o + "OLEObject";
        public static readonly XName oned = o + "oned";
        public static readonly XName opacity2 = o + "opacity2";
        public static readonly XName preferrelative = o + "preferrelative";
        public static readonly XName proxy = o + "proxy";
        public static readonly XName r = o + "r";
        public static readonly XName regroupid = o + "regroupid";
        public static readonly XName regrouptable = o + "regrouptable";
        public static readonly XName rel = o + "rel";
        public static readonly XName relationtable = o + "relationtable";
        public static readonly XName relid = o + "relid";
        public static readonly XName right = o + "right";
        public static readonly XName rules = o + "rules";
        public static readonly XName shapedefaults = o + "shapedefaults";
        public static readonly XName shapelayout = o + "shapelayout";
        public static readonly XName signatureline = o + "signatureline";
        public static readonly XName singleclick = o + "singleclick";
        public static readonly XName skew = o + "skew";
        public static readonly XName spid = o + "spid";
        public static readonly XName spt = o + "spt";
        public static readonly XName suggestedsigner = o + "suggestedsigner";
        public static readonly XName suggestedsigner2 = o + "suggestedsigner2";
        public static readonly XName suggestedsigneremail = o + "suggestedsigneremail";
        public static readonly XName tablelimits = o + "tablelimits";
        public static readonly XName tableproperties = o + "tableproperties";
        public static readonly XName targetscreensize = o + "targetscreensize";
        public static readonly XName title = o + "title";
        public static readonly XName top = o + "top";
        public static readonly XName userdrawn = o + "userdrawn";
        public static readonly XName userhidden = o + "userhidden";
        public static readonly XName v = o + "v";
    }
}